In [1]:
import pandas as pd 
import keras
from keras.preprocessing.text import Tokenizer, text_to_word_sequence
from keras.preprocessing.sequence import pad_sequences
from nltk.tokenize import word_tokenize


Using TensorFlow backend.


In [0]:
from keras.datasets import imdb

(train_data, train_labels), (test_data, test_labels) = imdb.load_data(num_words=10000)

In [3]:
train_data.shape

(25000,)

In [4]:
train_data[1]

[1,
 194,
 1153,
 194,
 8255,
 78,
 228,
 5,
 6,
 1463,
 4369,
 5012,
 134,
 26,
 4,
 715,
 8,
 118,
 1634,
 14,
 394,
 20,
 13,
 119,
 954,
 189,
 102,
 5,
 207,
 110,
 3103,
 21,
 14,
 69,
 188,
 8,
 30,
 23,
 7,
 4,
 249,
 126,
 93,
 4,
 114,
 9,
 2300,
 1523,
 5,
 647,
 4,
 116,
 9,
 35,
 8163,
 4,
 229,
 9,
 340,
 1322,
 4,
 118,
 9,
 4,
 130,
 4901,
 19,
 4,
 1002,
 5,
 89,
 29,
 952,
 46,
 37,
 4,
 455,
 9,
 45,
 43,
 38,
 1543,
 1905,
 398,
 4,
 1649,
 26,
 6853,
 5,
 163,
 11,
 3215,
 2,
 4,
 1153,
 9,
 194,
 775,
 7,
 8255,
 2,
 349,
 2637,
 148,
 605,
 2,
 8003,
 15,
 123,
 125,
 68,
 2,
 6853,
 15,
 349,
 165,
 4362,
 98,
 5,
 4,
 228,
 9,
 43,
 2,
 1157,
 15,
 299,
 120,
 5,
 120,
 174,
 11,
 220,
 175,
 136,
 50,
 9,
 4373,
 228,
 8255,
 5,
 2,
 656,
 245,
 2350,
 5,
 4,
 9837,
 131,
 152,
 491,
 18,
 2,
 32,
 7464,
 1212,
 14,
 9,
 6,
 371,
 78,
 22,
 625,
 64,
 1382,
 9,
 8,
 168,
 145,
 23,
 4,
 1690,
 15,
 16,
 4,
 1355,
 5,
 28,
 6,
 52,
 154,
 462,
 33,
 89,
 78,
 2

In [5]:
max([max(sequence) for sequence in train_data])

9999

In [6]:
for i in range(0, len(train_data)):
    print(len(train_data[i]))

218
189
141
550
147
43
123
562
233
130
450
99
117
238
109
129
163
752
212
177
129
140
256
888
93
142
220
193
171
221
174
647
233
162
597
234
51
336
139
231
704
142
861
132
122
570
55
214
103
186
113
169
469
138
302
766
351
146
59
206
107
152
186
431
147
684
383
324
252
263
787
211
314
118
390
132
710
306
167
115
95
158
156
82
502
314
190
174
60
145
214
659
408
515
461
202
238
170
107
171
158
145
790
258
287
67
123
975
775
236
195
274
214
91
1038
815
183
206
50
118
147
141
60
56
439
439
213
144
533
303
203
563
129
153
55
92
174
187
183
165
78
198
156
223
127
61
362
84
57
176
159
57
159
165
213
194
149
130
203
19
98
466
525
130
322
153
408
215
472
143
136
354
260
319
125
209
282
810
142
240
148
198
193
123
128
103
479
345
263
165
205
333
184
92
177
335
120
121
259
180
160
114
59
343
513
133
206
152
206
572
153
139
151
129
129
196
433
199
140
311
151
200
584
127
513
781
932
526
161
646
135
52
267
174
185
219
81
219
131
153
270
644
155
546
284
85
293
155
358
45
231
124
178
118
260
393
127


In [7]:
#padding the sequences to make them of same length
#train_data = pad_sequences(train_data , maxlen = 250)
train_data.shape

(25000,)

In [0]:
import numpy as np

def vectorize_sequences(sequences, dimension=10000):
    # Create an all-zero matrix of shape (len(sequences), dimension)
    results = np.zeros((len(sequences), dimension))
    for i, sequence in enumerate(sequences):
        results[i, sequence] = 1.  # set specific indices of results[i] to 1s
    return results

# Our vectorized training data
x_train = vectorize_sequences(train_data)
# Our vectorized test data
x_test = vectorize_sequences(test_data)

In [10]:
x_train

array([[0., 1., 1., ..., 0., 0., 0.],
       [0., 1., 1., ..., 0., 0., 0.],
       [0., 1., 1., ..., 0., 0., 0.],
       ...,
       [0., 1., 1., ..., 0., 0., 0.],
       [0., 1., 1., ..., 0., 0., 0.],
       [0., 1., 1., ..., 0., 0., 0.]])

In [11]:
x_train.shape


(25000, 10000)

In [0]:
# Our vectorized labels
y_train = np.asarray(train_labels).astype('float32')
y_test = np.asarray(test_labels).astype('float32')

In [13]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression()
model.fit(x_train, y_train)

/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [14]:
y_pred = model.predict(x_test)
y_pred

array([0., 1., 0., ..., 0., 0., 1.], dtype=float32)

In [15]:
from sklearn.metrics import classification_report, confusion_matrix

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

         0.0       0.86      0.86      0.86     12500
         1.0       0.86      0.86      0.86     12500

   micro avg       0.86      0.86      0.86     25000
   macro avg       0.86      0.86      0.86     25000
weighted avg       0.86      0.86      0.86     25000



In [0]:
from sklearn import metrics

In [17]:
print(metrics.accuracy_score(y_test, y_pred))

0.86204


In [18]:
print(confusion_matrix(y_test, y_pred))

[[10812  1688]
 [ 1761 10739]]


In [24]:
x_train.shape[1]

10000

In [0]:
from keras.models import Sequential
from keras.layers import Dense, Dropout

model = Sequential()
model.add(Dense(64, activation='relu', input_shape=x_train.shape[1]))
model.add(Dropout(0.3))

model.add(Dense(32, activation='relu')
model.add(Dense(1))

In [0]:
param = {'C':[1, 10, 100, 1000], 'gamma':[0.1, 0.01, 1, 0.001], 'kernel':['linear', 'rbf']}

In [0]:
from sklearn.model_selection import GridSearchCV

CV = GridSearchCV(model, param_grid=param, n_jobs= -1, cv=10)


In [0]:
CV.fit(X_train, y_train)

GridSearchCV(cv=10, error_score='raise',
       estimator=SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False),
       fit_params=None, iid=True, n_jobs=-1,
       param_grid={'C': [1, 10, 100, 1000], 'gamma': [0.1, 0.01, 1, 0.001], 'kernel': ['linear', 'rbf']},
       pre_dispatch='2*n_jobs', refit=True, return_train_score='warn',
       scoring=None, verbose=0)

In [0]:
CV.best_params_

{'C': 100, 'gamma': 0.01, 'kernel': 'rbf'}

In [0]:
CV.best_score_

0.8117283950617284

In [0]:
y_pred = CV.predict(X_test)
y_pred

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
       1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0,
       1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int64)

In [0]:
print(metrics.accuracy_score(y_test, y_pred))

0.7914110429447853


In [0]:
from sklearn.metrics import classification_report, confusion_matrix

print(classification_report(y_test, y_pred))

             precision    recall  f1-score   support

          0       0.42      0.26      0.32        31
          1       0.84      0.92      0.88       132

avg / total       0.76      0.79      0.77       163



In [0]:
confusion_matrix(y_test, y_pred)

array([[  8,  23],
       [ 11, 121]], dtype=int64)

In [0]:
tokenize = Tokenizer()
tokenize.fit_on_texts(transcript['text'])
seq = tokenize.texts_to_sequences(transcript['text'])
pad = pad_sequences(seq , maxlen = 150)
word_idx = tokenize1.word_index
features = pad
features
#features.shape

array([[   0,    0,    0, ..., 1137, 1477,  667],
       [   0,    0,    0, ...,  426,   51,   70],
       [   0,    0,    0, ...,  535, 1025,  276],
       ...,
       [   0,    0,    0, ...,  187, 1176,  709],
       [   0,    0,    0, ...,  137, 1133,  960],
       [   0,    0,    0, ...,  116, 1527,  474]])